name: transmute
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/my_org/my_repo
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  properties: ^2.1.0
  dart_openai: ^3.0.0
  serviced: ^1.0.1
  fast_log: ^1.0.5
  toxic: ^1.0.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
